name: Deploy Open Brew example to S3

on:
  push:
    branches:
      - master

env:
  AWS_REGION: eu-central-1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy definitions S3 bucket
      run: aws s3 sync ./v1.0.0/ s3://openbrew-definition-prod --delete

    - name: Deploy api-spec to S3 bucket
      run: aws s3 sync ./api/ s3://openbrew-definition-prod